//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RejestrUprawnien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uprawnienie
    {
        public int id { get; set; }
        public int id_pracownik { get; set; }
        public int id_zasob { get; set; }
        public Nullable<int> id_poziom { get; set; }
        public Nullable<System.DateTime> data_utworzenia { get; set; }
        public Nullable<System.DateTime> data_zatwierdzenia { get; set; }
        public Nullable<System.DateTime> data_usunięcia { get; set; }
        public string zatwierdzil { get; set; }
        public string utworzyl { get; set; }
        public string usunal { get; set; }
        public int id_nazwa_zasobu { get; set; }
    
        public virtual Nazwa_zasobu Nazwa_zasobu { get; set; }
        public virtual Poziom_uprawnien Poziom_uprawnien { get; set; }
        public virtual Pracownik Pracownik { get; set; }
        public virtual Zasob Zasob { get; set; }
    }
}
